from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field

from shared.models.crawl_models import AuthConfig, CrawlRequest, DiscoveredURL
from shared.models.page_models import CrawlResult, PageData


class OrchestratorPhase(str, Enum):
    START = "start"
    PLAN = "plan"
    AUTH = "auth"
    CRAWL = "crawl"
    CLASSIFY = "classify"
    EXTRACT = "extract"
    EVALUATE = "evaluate"
    COMPLETE = "complete"
    FAILED = "failed"


class CrawlPlan(BaseModel):
    """Strategic plan generated by the Planner."""
    expected_page_types: list[str] = Field(default_factory=list)
    needs_auth: bool = False
    priority_areas: list[str] = Field(default_factory=list)
    estimated_page_count: int = 50
    strategy_notes: str = ""


class OrchestratorState(BaseModel):
    """The central state that flows through the LangGraph state machine."""
    # Input
    request: CrawlRequest

    # Phase tracking
    phase: OrchestratorPhase = OrchestratorPhase.START
    iteration: int = 0

    # Plan
    plan: Optional[CrawlPlan] = None

    # Auth
    auth_success: bool = False
    auth_session: Optional[dict] = None
    storage_state_path: Optional[str] = None

    # Crawl state
    url_frontier: list[DiscoveredURL] = Field(default_factory=list)
    visited_urls: set[str] = Field(default_factory=set)
    pages: list[PageData] = Field(default_factory=list)

    # Evaluation
    coverage_score: float = 0.0
    should_continue: bool = True
    new_urls_this_iteration: int = 0

    # Result
    result: Optional[CrawlResult] = None

    # Errors
    errors: list[str] = Field(default_factory=list)

    class Config:
        arbitrary_types_allowed = True
